import json
import re
from typing import List, Dict, Any
from pydantic import BaseModel, Field
from langchain_openai import ChatOpenAI
from langchain_core.prompts import ChatPromptTemplate
from core.schemas import TeachingStep
from core.interfaces import ILLMService
from langchain_core.language_models.chat_models import BaseChatModel

# ==========================================
# INGESTION SCHEMAS (UPDATED FOR GRAPH ONTOLOGY)
# ==========================================
class GraphNode(BaseModel):
    """
    - Reason: To explicitly define entities with their categorical types and a short summary.
    - Function: Validates the 'nodes' array generated by the LLM.
    - Usage: Used within the KnowledgeGraph schema.
    """
    name: str = Field(description="Name of the concept/entity")
    type: str = Field(description="Type/category of the node (e.g., graph, matrix, concept, algorithm)")
    description: str = Field(description="A very short description (1 sentence) of the concept based on the text")

class GraphEdge(BaseModel):
    """
    - Reason: To define the relationships between GraphNodes.
    - Function: Validates the 'edges' array generated by the LLM.
    - Usage: Used within the KnowledgeGraph schema.
    - Parameters: None.
    - Returns: Pydantic Model.
    """
    source: str
    relation: str = Field(description="Strictly use: PREREQUISITE_OF, RELATES_TO, PART_OF, DESCRIBES")
    target: str

class KnowledgeGraph(BaseModel):
    """
    - Reason: To enclose nodes and edges into a standard Ontology structure.
    - Function: Acts as the main container for the DAG extraction task.
    - Usage: Used within SectionExtraction.
    - Parameters: None.
    - Returns: Pydantic Model.
    """
    nodes: List[GraphNode]
    edges: List[GraphEdge]

class SectionExtraction(BaseModel):
    main_entities: List[str] = Field(description="The main entities or primary objectives described in the section")
    teaching_roadmap: List[TeachingStep] = Field(description="The teaching roadmap including the agent queue")
    knowledge_graph: KnowledgeGraph = Field(description="The extracted knowledge graph with nodes and edges")

class QuestionList(BaseModel):
    questions: List[str]

# ==========================================
# LOCAL LLM SERVICE ORCHESTRATOR
# ==========================================
class LLMService(ILLMService):
    def __init__(self, llm: BaseChatModel, chat_llm: BaseChatModel):
        """
        - Function: Initializes the connection using injected LLM instances.
        """
        self.llm = llm
        self.chat_llm = chat_llm

    def _extract_json_from_text(self, text: str) -> str:
        """
        - Reason: As a safety net in case the LLM wraps the JSON in markdown code blocks despite JSON mode.
        - Function: Uses Regular Expressions to pinpoint and extract pure JSON.
        - Usage: Internal helper called after every LLM generation.
        - Parameters:
            - text (str): The raw text output from the LLM.
        - Returns: A cleaned JSON string.
        - Alternatives: Direct JSON parsing.
        """
        fence = "```"
        pattern = fence + r"(?:json)?\s*(.*?)\s*" + fence

        match = re.search(pattern, text, re.DOTALL)
        if match:
            return match.group(1)

        start_idx = text.find('{')
        end_idx = text.rfind('}')
        if start_idx != -1 and end_idx != -1 and end_idx > start_idx:
            return text[start_idx:end_idx + 1]

        start_idx_arr = text.find('[')
        end_idx_arr = text.rfind(']')
        if start_idx_arr != -1 and end_idx_arr != -1 and end_idx_arr > start_idx_arr:
            return text[start_idx_arr:end_idx_arr + 1]

        return text

    def extract_section_curriculum_and_dag(self, section_text: str, existing_nodes: List[str] = None) -> Dict[str, Any]:
        """
        - Reason: Replaces the Runtime Router. Performs AOT routing, Ontology extraction, and Entity Tagging.
        - Function: Extracts main entities, teaching roadmap, and the structured knowledge graph.
        - Usage: Called by the data ingestion pipeline.
        - Parameters:
            - section_text (str): The raw text of the textbook section.
        - Returns: A dictionary containing 'main_entities', 'teaching_roadmap', and 'knowledge_graph'.
        - Alternatives: Sequential LLM chains (slower).
        """
        if existing_nodes is None: existing_nodes = []
        json_format = """
        {
            "main_entities": ["Entity 1", "Entity 2"],
            "teaching_roadmap": [
                {
                    "step_id": "step_1",
                    "step_title": "String",
                    "content_focus": "Exact verbatim text quote",
                    "required_agents": ["concept", "formula"]
                }
            ],
            "knowledge_graph": {
                "nodes": [
                    {"name": "Concept A", "type": "category", "description": "1-sentence summary"}
                ],
                "edges": [
                    {"source": "Concept A", "relation": "RELATES_TO", "target": "Concept B"}
                ]
            }
        }
        """

        prompt = ChatPromptTemplate.from_messages([
            ("system",
             "You are an advanced Data Extraction API. Your sole purpose is to process textual information and output strictly valid JSON. Any conversational text, markdown outside of the JSON block, or hallucinated fields will cause a critical system failure. Always return a raw JSON object."),
            ("human", """
            Please analyze the provided textbook section and perform the following three extraction tasks:

            ### TASK 1: MAIN ENTITIES EXTRACTION
            - Identify the primary subjects, core concepts, or main objectives discussed in the text.
            - Output them as a simple array of strings in the `main_entities` field.

            ### TASK 2: TEACHING ROADMAP & AGENT ROUTING
            - Aggregate the text into broad, comprehensive teaching steps. Group related paragraphs together.
            - CRITICAL LIMIT: Create a MAXIMUM of 2 to 4 steps for the entire section. Do NOT create a step for every single paragraph.
            - For each step, extract a `step_title` and a `content_focus` (which MUST be an exact verbatim quote summarizing the step).
            - Assign a `required_agents` array (Max 1-3 agents per step) based strictly on this registry: 'concept', 'formula', 'math', 'algorithm', 'example', 'dynamic:<role>'.

            ### TASK 3: KNOWLEDGE GRAPH ONTOLOGY EXTRACTION
            - Extract a structured knowledge graph containing `nodes` and `edges`.
            - Nodes: Extract key concepts. Assign them a logical `type` and a very short (1 sentence) `description` based on the text.
            - Edges: Map the relationships between these nodes. Allowed relations: PREREQUISITE_OF, RELATES_TO, PART_OF, DESCRIBES.
            
            [CRITICAL LINKING RULE]: 
            You are provided with a list of concepts already extracted from previous sections. 
            If a concept in the text matches or is synonymous with an item in [EXISTING KNOWLEDGE GRAPH NODES], you MUST use the exact name from the existing list.
            If the text implies a relationship between a new concept and an existing concept, CREATE AN EDGE connecting them.

            ---
            [EXISTING KNOWLEDGE GRAPH NODES]:
            {existing_nodes}

            [SOURCE TEXT TO ANALYZE]:
            {section_text}
            ---

            ### STRICT JSON FORMAT INSTRUCTIONS:
            You MUST wrap your entire response exactly in the following JSON structure. Do NOT add any conversational text before or after the JSON.

            {format_instructions}
            """)
        ])

        _input = prompt.format_messages(
            section_text=section_text,
            existing_nodes=", ".join(existing_nodes) if existing_nodes else "None",
            format_instructions=json_format
        )

        print("\n[*] Invoking Qwen for AOT Routing, Entities, and DAG Ontology Extraction...")
        raw_response = self.llm.invoke(_input)

        clean_json_str = self._extract_json_from_text(raw_response.content)

        try:
            parsed_dict = json.loads(clean_json_str)
            validated_data = SectionExtraction(**parsed_dict)
            return validated_data.model_dump()
        except Exception as e:
            print(f"[!] JSON Parse Error (LLM Format Hallucination): {e}")
            print(f"RAW OUTPUT:\n{raw_response.content}")
            return {"main_entities": [], "teaching_roadmap": [], "knowledge_graph": {"nodes": [], "edges": []}}

    def generate_hypothetical_questions(self, section_text: str, num_questions: int = 5) -> List[Dict[str, str]]:
        """
        - Reason: To implement HyDE (Hypothetical Document Embeddings).
        - Function: Generates FAQ-style questions and their concise answers (Key Knowledge).
        """
        prompt = ChatPromptTemplate.from_messages([
            ("system",
             "YOU ARE A STRICT DATA EXTRACTION API. Output ONLY a valid JSON object. No extra text."),
            ("human", """
            Generate exactly {num_questions} FAQ questions and their extremely concise answers (Key Knowledge) based ONLY on the text.
            Each Key Knowledge should be a 1-2 sentence technical summary that answers the question perfectly.

            [SOURCE TEXT]: 
            {section_text}

            [REQUIRED JSON FORMAT]:
            {{
                "qa_pairs": [
                    {{"question": "What is X?", "key_knowledge": "X is a method for... It works by..."}},
                    ...
                ]
            }}
            """)
        ])

        _input = prompt.format_messages(num_questions=num_questions, section_text=section_text)

        raw_response = self.llm.invoke(_input)
        clean_json_str = self._extract_json_from_text(raw_response.content)

        try:
            parsed_dict = json.loads(clean_json_str)
            return parsed_dict.get("qa_pairs", [])
        except Exception as e:
            print(f"[!] Question Generation Error: {e}")
            return []

    def generate_quiz(self, section_text: str) -> tuple[List[Dict], Optional[str]]:
        """
        - Function: Generates a list of multiple choice questions based on section content.
        """
        if not section_text or len(section_text.strip()) < 50:
            return [], "Section text is too short to generate a meaningful quiz."

        prompt = f"""
        You are an expert examiner. Based on the following educational content, generate exactly 3 high-quality multiple choice questions (MCQs).
        
        Content:
        {section_text}
        
        Return ONLY a JSON list:
        [
            {{
                "question": "text",
                "options": ["A", "B", "C", "D"],
                "answer_idx": 0,
                "explanation": "text"
            }}
        ]
        """
        try:
            raw_response = self.llm.invoke(prompt)
            content = raw_response.content
            
            clean_json_str = self._extract_json_from_text(content)
            
            try:
                quiz_data = json.loads(clean_json_str)
                if isinstance(quiz_data, list) and len(quiz_data) > 0:
                    return quiz_data, None
                return [], f"AI returned empty or invalid list format. Raw: {content[:100]}..."
            except json.JSONDecodeError:
                return [], f"JSON Parse Error. AI output was: {content[:200]}..."
        except Exception as e:
            return [], f"LLM Invocation Error: {str(e)}"

    def generate_source_briefing(self, file_name: str, full_text: str) -> tuple[Dict, Optional[str]]:
        """
        - Function: Generates a high-level briefing based on the ACTUAL FULL CONTENT.
        """
        prompt = f"""
        You are an expert academic researcher. Based on the FULL CONTENT of the document '{file_name}' provided below, generate a comprehensive 'Source Briefing'.
        Everything must be grounded in the text. Do NOT hallucinate.
        
        [FULL DOCUMENT CONTENT]:
        {full_text[:100000]}
        
        Return ONLY a JSON object:
        {{
            "synopsis": "...",
            "key_themes": ["...", "..."],
            "podcast_script": "..."
        }}
        """
        try:
            raw_response = self.llm.invoke(prompt)
            content = raw_response.content
            clean_json_str = self._extract_json_from_text(content)
            
            try:
                data = json.loads(clean_json_str)
                return data, None
            except json.JSONDecodeError:
                return {}, f"Briefing JSON Error. AI output was: {content[:200]}..."
        except Exception as e:
            return {}, f"Briefing LLM Error: {str(e)}"

    def rerank_candidate_questions(self, user_query: str, candidates: List[Dict[str, str]]) -> List[str]:
        """
        - Reason: Rerank vector search results using LLM reasoning.
        - Function: Identifies the 1-2 hypothetical questions most semantically similar to the user's query.
        - Returns: A list of unique 'parent_id's.
        """
        if not candidates:
            return ""
            
        candidates_str = json.dumps(candidates, ensure_ascii=False, indent=2)
        
        prompt = ChatPromptTemplate.from_messages([
            ("system", 
             "You are a strict semantic matching API. Your job is to select the candidate question that best matches the intent of the User Query. Return ONLY a valid JSON object. No markdown formatting outside the JSON block. Do not converse."),
            ("human", """
            [USER QUERY]:
            {user_query}
            
            [CANDIDATE QUESTIONS]:
            {candidates}
            
            Find the 1 or 2 candidates that best match the intent of the User Query. 
            If multiple candidates point to the same parent_id, only include that parent_id once.
            
            [REQUIRED JSON FORMAT]:
            {{
                "best_parent_ids": ["id_1", "id_2"]
            }}
            """)
        ])
        
        _input = prompt.format_messages(user_query=user_query, candidates=candidates_str)
        
        try:
            raw_response = self.llm.invoke(_input)
            clean_json_str = self._extract_json_from_text(raw_response.content)
            parsed_dict = json.loads(clean_json_str)
            ids = parsed_dict.get("best_parent_ids", [])
            if not ids and candidates:
                return [candidates[0].get("parent_id", "")]
            return list(dict.fromkeys(ids)) # Deduplicate while preserving order
        except Exception as e:
            print(f"[!] Rerank Error: {e}")
            if candidates: return [candidates[0].get("parent_id", "")]
            return []