import json
import re
from typing import List, Dict, Any
from pydantic import BaseModel, Field
from langchain_openai import ChatOpenAI
from langchain_core.prompts import ChatPromptTemplate
from core.schemas import TeachingStep
from config.settings import LLM_MODEL_NAME, TEMPERATURE, TOP_P

# ==========================================
# INGESTION SCHEMAS (UPDATED FOR GRAPH ONTOLOGY)
# ==========================================
class GraphNode(BaseModel):
    """
    - Reason: To explicitly define entities with their categorical types.
    - Function: Validates the 'nodes' array generated by the LLM.
    - Usage: Used within the KnowledgeGraph schema.
    - Parameters: None.
    - Returns: Pydantic Model.
    """
    name: str = Field(description="Name of the concept/entity")
    type: str = Field(description="Type/category of the node (e.g., graph, matrix, concept, algorithm)")

class GraphEdge(BaseModel):
    """
    - Reason: To define the relationships between GraphNodes.
    - Function: Validates the 'edges' array generated by the LLM.
    - Usage: Used within the KnowledgeGraph schema.
    - Parameters: None.
    - Returns: Pydantic Model.
    """
    source: str
    relation: str = Field(description="Strictly use: PREREQUISITE_OF, RELATES_TO, PART_OF, DESCRIBES")
    target: str

class KnowledgeGraph(BaseModel):
    """
    - Reason: To enclose nodes and edges into a standard Ontology structure.
    - Function: Acts as the main container for the DAG extraction task.
    - Usage: Used within SectionExtraction.
    - Parameters: None.
    - Returns: Pydantic Model.
    """
    nodes: List[GraphNode]
    edges: List[GraphEdge]

class SectionExtraction(BaseModel):
    main_entities: List[str] = Field(description="The main entities or primary objectives described in the section")
    teaching_roadmap: List[TeachingStep] = Field(description="The teaching roadmap including the agent queue")
    knowledge_graph: KnowledgeGraph = Field(description="The extracted knowledge graph with nodes and edges")

class QuestionList(BaseModel):
    questions: List[str]

# ==========================================
# LOCAL LLM SERVICE ORCHESTRATOR
# ==========================================
class LLMService:
    def __init__(self):
        """
        - Reason: To utilize local GPU (RTX 3060 12GB) and enforce strict JSON generation.
        - Function: Initializes the connection to the local Qwen model via Ollama with JSON Mode enabled.
        - Usage: Instantiated once at system startup.
        - Parameters: None.
        - Returns: None.
        - Alternatives: vLLM endpoint.
        """
        self.llm = ChatOpenAI(
            base_url="http://localhost:11434/v1",
            api_key="not-needed",
            model=LLM_MODEL_NAME,
            temperature=TEMPERATURE,  # Absolute zero for deterministic output
            top_p= TOP_P,
            max_tokens=2048,
            model_kwargs={
                "response_format": {"type": "json_object"}
            }
        )

        # [NEW]: Dedicated LLM instance for generating raw markdown (bypasses JSON restrictions)
        self.chat_llm = ChatOpenAI(
            base_url="http://localhost:11434/v1",
            api_key="not-needed",
            model=LLM_MODEL_NAME,
            temperature=0.3,
            max_tokens=4096
        )

    def _extract_json_from_text(self, text: str) -> str:
        """
        - Reason: As a safety net in case the LLM wraps the JSON in markdown code blocks despite JSON mode.
        - Function: Uses Regular Expressions to pinpoint and extract pure JSON.
        - Usage: Internal helper called after every LLM generation.
        - Parameters:
            - text (str): The raw text output from the LLM.
        - Returns: A cleaned JSON string.
        - Alternatives: Direct JSON parsing.
        """
        fence = "```"
        pattern = fence + r"(?:json)?\s*(.*?)\s*" + fence

        match = re.search(pattern, text, re.DOTALL)
        if match:
            return match.group(1)

        start_idx = text.find('{')
        end_idx = text.rfind('}')
        if start_idx != -1 and end_idx != -1 and end_idx > start_idx:
            return text[start_idx:end_idx + 1]

        start_idx_arr = text.find('[')
        end_idx_arr = text.rfind(']')
        if start_idx_arr != -1 and end_idx_arr != -1 and end_idx_arr > start_idx_arr:
            return text[start_idx_arr:end_idx_arr + 1]

        return text

    def extract_section_curriculum_and_dag(self, section_text: str, existing_nodes: List[str] = None) -> Dict[str, Any]:
        """
        - Reason: Replaces the Runtime Router. Performs AOT routing, Ontology extraction, and Entity Tagging.
        - Function: Extracts main entities, teaching roadmap, and the structured knowledge graph.
        - Usage: Called by the data ingestion pipeline.
        - Parameters:
            - section_text (str): The raw text of the textbook section.
        - Returns: A dictionary containing 'main_entities', 'teaching_roadmap', and 'knowledge_graph'.
        - Alternatives: Sequential LLM chains (slower).
        """
        if existing_nodes is None: existing_nodes = []
        json_format = """
        {
            "main_entities": ["Entity 1", "Entity 2"],
            "teaching_roadmap": [
                {
                    "step_id": "step_1",
                    "step_title": "String",
                    "content_focus": "Exact verbatim text quote",
                    "required_agents": ["concept", "formula"]
                }
            ],
            "knowledge_graph": {
                "nodes": [
                    {"name": "Concept A", "type": "category"}
                ],
                "edges": [
                    {"source": "Concept A", "relation": "RELATES_TO", "target": "Concept B"}
                ]
            }
        }
        """

        prompt = ChatPromptTemplate.from_messages([
            ("system",
             "You are an advanced Data Extraction API. Your sole purpose is to process textual information and output strictly valid JSON. Any conversational text, markdown outside of the JSON block, or hallucinated fields will cause a critical system failure. Always return a raw JSON object."),
            ("human", """
            Please analyze the provided textbook section and perform the following three extraction tasks:

            ### TASK 1: MAIN ENTITIES EXTRACTION
            - Identify the primary subjects, core concepts, or main objectives discussed in the text.
            - Output them as a simple array of strings in the `main_entities` field.

            ### TASK 2: TEACHING ROADMAP & AGENT ROUTING
            - Aggregate the text into broad, comprehensive teaching steps. Group related paragraphs together.
            - CRITICAL LIMIT: Create a MAXIMUM of 2 to 4 steps for the entire section. Do NOT create a step for every single paragraph.
            - For each step, extract a `step_title` and a `content_focus` (which MUST be an exact verbatim quote summarizing the step).
            - Assign a `required_agents` array (Max 1-3 agents per step) based strictly on this registry: 'concept', 'formula', 'math', 'algorithm', 'example', 'dynamic:<role>'.

            ### TASK 3: KNOWLEDGE GRAPH ONTOLOGY EXTRACTION
            - Extract a structured knowledge graph containing `nodes` and `edges`.
            - Nodes: Extract key concepts and assign them a logical `type` (e.g., 'graph', 'matrix', 'system', 'theory').
            - Edges: Map the relationships between these nodes. Allowed relations: PREREQUISITE_OF, RELATES_TO, PART_OF, DESCRIBES.
            
            [CRITICAL LINKING RULE]: 
            You are provided with a list of concepts already extracted from previous sections. 
            If a concept in the text matches or is synonymous with an item in [EXISTING KNOWLEDGE GRAPH NODES], you MUST use the exact name from the existing list.
            If the text implies a relationship between a new concept and an existing concept, CREATE AN EDGE connecting them.

            ---
            [EXISTING KNOWLEDGE GRAPH NODES]:
            {existing_nodes}

            [SOURCE TEXT TO ANALYZE]:
            {section_text}
            ---

            ### STRICT JSON FORMAT INSTRUCTIONS:
            You MUST wrap your entire response exactly in the following JSON structure. Do NOT add any conversational text before or after the JSON.

            {format_instructions}
            """)
        ])

        _input = prompt.format_messages(
            section_text=section_text,
            existing_nodes=", ".join(existing_nodes) if existing_nodes else "None",
            format_instructions=json_format
        )

        print("\n[*] Invoking Qwen for AOT Routing, Entities, and DAG Ontology Extraction...")
        raw_response = self.llm.invoke(_input)

        clean_json_str = self._extract_json_from_text(raw_response.content)

        try:
            parsed_dict = json.loads(clean_json_str)
            validated_data = SectionExtraction(**parsed_dict)
            return validated_data.model_dump()
        except Exception as e:
            print(f"[!] JSON Parse Error (LLM Format Hallucination): {e}")
            print(f"RAW OUTPUT:\n{raw_response.content}")
            return {"main_entities": [], "teaching_roadmap": [], "knowledge_graph": {"nodes": [], "edges": []}}

    def generate_hypothetical_questions(self, section_text: str, num_questions: int = 5) -> List[str]:
        """
        - Reason: To improve retrieval accuracy using Hypothetical Document Embeddings (HyDE).
        - Function: Generates FAQ questions that act as semantic anchors.
        - Usage: Called immediately after roadmap extraction.
        - Parameters:
            - section_text (str): The raw text of the textbook section.
            - num_questions (int): Number of questions to generate.
        - Returns: A list of string questions.
        - Alternatives: Keyword extraction.
        """
        prompt = ChatPromptTemplate.from_messages([
            ("system",
             "YOU ARE A STRICT DATA EXTRACTION API. Output ONLY a valid JSON object containing an array of strings. No extra text."),
            ("human", """
            Generate exactly {num_questions} FAQ questions based on the text.

            [SOURCE TEXT]: 
            {section_text}

            [REQUIRED JSON FORMAT]:
            {{
                "questions": ["Question 1?", "Question 2?", ...]
            }}
            """)
        ])

        _input = prompt.format_messages(num_questions=num_questions, section_text=section_text)

        raw_response = self.llm.invoke(_input)
        clean_json_str = self._extract_json_from_text(raw_response.content)

        try:
            parsed_dict = json.loads(clean_json_str)
            return parsed_dict.get("questions", [])
        except Exception as e:
            print(f"[!] Question Generation Error: {e}")
            return []

    def rerank_candidate_questions(self, user_query: str, candidates: List[Dict[str, str]]) -> str:
        """
        - Reason: Rerank vector search results using LLM reasoning.
        - Function: Identifies the hypothetical question most semantically similar to the user's query.
        - Parameters:
            - user_query: The actual question from the user.
            - candidates: A list of dictionaries containing 'question' and 'parent_id'.
        - Returns: The best 'parent_id'. Falls back to the first candidate on error.
        """
        if not candidates:
            return ""
            
        candidates_str = json.dumps(candidates, ensure_ascii=False, indent=2)
        
        prompt = ChatPromptTemplate.from_messages([
            ("system", 
             "You are a strict semantic matching API. Your job is to select the candidate question that best matches the intent of the User Query. Return ONLY a valid JSON object. No markdown formatting outside the JSON block. Do not converse."),
            ("human", """
            [USER QUERY]:
            {user_query}
            
            [CANDIDATE QUESTIONS]:
            {candidates}
            
            Find the candidate that has the exact same semantic intent as the User Query.
            
            [REQUIRED JSON FORMAT]:
            {{
                "best_parent_id": "the parent_id of the best match"
            }}
            """)
        ])
        
        _input = prompt.format_messages(user_query=user_query, candidates=candidates_str)
        
        try:
            raw_response = self.llm.invoke(_input)
            clean_json_str = self._extract_json_from_text(raw_response.content)
            parsed_dict = json.loads(clean_json_str)
            return parsed_dict.get("best_parent_id", candidates[0].get("parent_id", ""))
        except Exception as e:
            print(f"[!] Rerank Error: {e}")
            if candidates: return candidates[0].get("parent_id", "")
            return ""